_target_: diffusion_policy.workspace.train_adaflow_unet_image_workspace.TrainAdaflowUnetImageWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  # batch_size: 64
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
# horizon: 16
horizon: 4
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2025.02.17-21.55.06_train_adaflow_unet_hybrid_metaworld_reach-wall_image
  project: adaflow_policy_NF
  resume: true
  tags:
  - train_adaflow_unet_hybrid
  - metaworld_reach-wall_image
  - default
multi_run:
  run_dir: data/outputs/2025.02.17/21.56.06_train_adaflow_unet_hybrid_metaworld_reach-wall_image
  wandb_name_base: 2025.02.17-21.56.06_train_adaflow_unet_hybrid_metaworld_reach-wall_image
# n_action_steps: 8
n_action_steps: 3
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false

policy:
  _target_: diffusion_policy.policy.adaflow_unet_image_policy.AdaflowUnetImagePolicy

  shape_meta: ${shape_meta}

  obs_encoder:
    _target_: diffusion_policy.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: diffusion_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: [127, 127]
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True

  horizon: 4
  n_action_steps: 3
  n_obs_steps: 2
  num_inference_steps: 10
  obs_as_global_cond: true
  diffusion_step_embed_dim: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  pos_emb_scale: 100

  pretrained_rf_ckpt: ""

shape_meta:
  action:
    shape:
    - 4
  obs:
    agent_pos:
      shape:
      - 9
      type: low_dim
    image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.dataset.metaworld_image_dataset.MetaworldImageDataset
    # horizon: 16
    horizon: 4
    max_train_episodes: 90
    # pad_after: 7
    pad_after: 2 # {n_action_steps}-1
    pad_before: 1 # {n_obs_steps}-1
    seed: 42
    val_ratio: 0.02
    zarr_path: data/ENV_NOTFreeze_10/metaworld_reach-wall_expert.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.metaworld_image_runner.MetaworldImageRunner
    eval_episodes: 20
    task_name: reach-wall
    fps: 10
    # legacy_test: true
    max_steps: 300
    # n_action_steps: 8
    n_action_steps: 3
    n_envs: null
    n_obs_steps: 2
    n_test: 50
    # n_test_vis: 4
    n_train: 6
    # n_train_vis: 2
    # past_action: false
    # test_start_seed: 100000
    # train_start_seed: 0
  image_shape:
  - 3
  - 128
  - 128
  name: pmetaworld_reach-wall_image
  shape_meta:
    action:
      shape:
      - 4
    obs:
      agent_pos:
        shape:
        - 9
        type: low_dim
      image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
task_name: metaworld_reach-wall_image
training:
  checkpoint_every: 200
  debug: False
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  # num_epochs: 3050
  num_epochs: 1000
  resume: true
  rollout_every: 200
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  freeze_encoder: False
  val_every: 1
val_dataloader:
  # batch_size: 64
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
